import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 10, y = 10 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "Fira Code iScript", style = "Italic" }
bold_italic = { family = "Fira Code iScript", style = "Bold Italic" }

size = 14.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "never" }
vi_mode_style = { shape = "Block", blinking = "never" }

[mouse]
hide_when_typing = true
