import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "screen-256color"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
opacity = 0.7
padding = { x = 3, y = 3 }
dynamic_padding = true

[font]
normal = { family = "BlexMono Nerd Font", style = "Regular" }
bold = { family = "BlexMono Nerd Font", style = "Bold" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Bold Italic" }

size = 12.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "never" }
vi_mode_style = { shape = "Block", blinking = "never" }

[mouse]
hide_when_typing = true
